### PR TITLE
http.get takes a uri as an argument but was served an unparsed string

### PR DESCRIPTION
**Pull request by ColleSerre**

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
The [http](https://pub.dev/packages/http) package is used here, Uri or String can be used

From code comments
```dart
  /// Sends an HTTP GET request with the given headers to the given URL, which
  /// can be a [Uri] or a [String].
  ///
  /// For more fine-grained control over the request, use [send] instead.
  Future<Response> get(url, {Map<String, String> headers});
```

**Comment by ColleSerre** [comment]
Woops, idk it just popped up red in vs code so I figured I'd open a pr,
you're welcome to close it.

Le mar. 23 mars 2021 à 23:57, CloudWebRTC ***@***.***> a
écrit :

**Comment by ghenry** [comment]
The latest http in dart doesn’t take a string.--
Kind Regards,

Gavin Henry.
Managing Director.

T +44 (0) 330 44 50 000
D +44 (0) 330 44 55 007
M +44 (0) 7930 323266
F +44 (0) 1224 824887
E ***@***.***

Open Source. Open Solutions(tm).

http://www.suretecsystems.com/

Suretec Systems is a limited company registered in Scotland. Registered
number: SC258005. Registered office: 24 Cormack Park, Rothienorman,
Inverurie, Aberdeenshire, AB51 8GL.

Subject to disclaimer at http://www.suretecgroup.com/disclaimer.html

**Comment by ColleSerre** [comment]
Oh so that's why, I'm running the latest dev channel version so, makes
sense.

Le mer. 24 mars 2021 à 00:34, Gavin Henry ***@***.***> a
écrit :

**Comment by cloudwebrtc** [comment]
@ColleSerre  I think it can be merged for compatibility. I checked the older version that can support Uri, so I will merge it

**Pull request merged**
