### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by lumec**
Fix spelling

### CODE REVIEW

**Comment by ycherniavskyi** [comment]
As for me commit has the odd name for now - "Update signaling.dart" (and yes in history I also see the same naming, but it does not mean that they are not odd 😊).
I propose to rename commit for example to "Fix spelling" (yes it is your PR comment 😊).

**Comment by lumec** [comment]
I've already renamed the commit as you suggested. I hope my first commit can be taken into account :)

**Comment by ycherniavskyi** [comment]
@lumec sorry it seems that my explanation was not clear enough. For now, I see that you rename PR title, but I mean to rename commit message.
Now it is:
```
Update signaling.dart

Fix spelling
```
I propused to chane it to:
```
Fix spelling
```

For this, you need to amend your last commit message and the push new version with [force flag](https://git-scm.com/docs/git-push#Documentation/git-push.txt--f).

My intention of such renaming is that from commit, we already see what files it modifies/update, so no reason to write about it, especially in the title.

**Comment by ycherniavskyi** [comment]
@lumec are you going to apply to commit message update, which I described in the previous comment?

**Comment by lumec** [comment]
@ycherniavskyi yeah.. I made the changes that you recommended. I would a pleasure if you checked my commit and gave me the feedback

**Comment by ycherniavskyi** [comment]
@lumec thank you for your PR and sorry for such hypercritical review 😉.

**Pull request merged**
